version: '3'
services:
  database:
    image: mysql:8.0.25
    container_name: mysql_db
    volumes:
      - ./db/db-setup:/docker-entrypoint-initdb.d/:ro
      - ./db/data:/var/lib/mysql:rw
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: cbom_maker
      MYSQL_USER: user
      MYSQL_PASSWORD: password123
      MYSQL_ROOT_PASSWORD: rootPassword123